# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Deploying to food-organisator

on: [ push, workflow_dispatch ]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "{{ TINY_API_KEY }}"
          replace: ${{ secrets.TINY_API_KEY }}
          include: "environment.prod.ts"

      - name: Set up Node Build front with node
        uses: actions/setup-node@v1
        with:
          node-version: 18.20.3

      - name: Build front
        run: npm install && npm run test && npm run build-prod

      - name: Copy front to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "dist/browser"
          target: "work/dist_from_github_teacher"

      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: cd work && sh deploy-teacher-from-dist.sh
